[package]
name = "it_db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.10"
diesel = { version = "2.1.0", features = ["postgresql"] }
dotenv = "0.15.0"
